version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: book_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
